"""empty message

Revision ID: eed29b72cc2b
Revises: 1f85bcac3eff
Create Date: 2019-01-09 20:43:57.232451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed29b72cc2b'
down_revision = '1f85bcac3eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
